### PR TITLE
update to msx 0.4.1

### PR DESCRIPTION
**Pull request by PierreGambarotto**
A simple update to msx.

### CODE REVIEW

**Comment by codematix** [comment]
Hi @sdemjanenko, any ETA on when this can get merged? Your loader seems to be a useful one. However, its dependencies are out-of-date.

**Comment by sdemjanenko** [comment]
Merged and published.  You should be able to use 0.3.0.  Sorry I didn't see this PR until just now.

**Comment by codematix** [comment]
@sdemjanenko @PierreGambarotto thanks for this!

**Comment by PierreGambarotto** [comment]
Perfect ! Thanks @sdemjanenko

**Pull request merged**
